config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :listings, except: :show
  end
  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', as: :logout
  get 'welcome', to: 'welcome#index'
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user

  validates :zipcode, presence: true, length: { maximum: 5, minimum: 5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, dependent: :destroy
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: :index

  def index
    @listings = Listing.all
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ update ]
  def new
    @listing = current_user.listings.new
  end

  def edit
    @user = current_user
    @listing = @user.listings.find(params[:id])
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      redirect_to user_path(current_user), notice: 'Listing was created successfully'
    else
      render :new
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to user_path(current_user), notice: "Listing was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.destroy
    redirect_to user_path(current_user), notice: "Listing was deleted"
  end

  private
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:title, :description, :zipcode, :price)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        #format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.html { redirect_to(user_url(@user), notice: 'User was successfully created') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>Find a place to rest tonight!</h1>
<p>Wanderers of the world rejoice. What happens when you cross AirBnb and Zillow? Pillow, an app to help you find a room to sleep for the night!</p>

<%= link_to "All users", users_path %>

<hr>

<% if @listings.any? %>
  <h2>All listings</h2>
  <ul>
    <% @listings.each do |listing| %>
      <li><%= listing.title %></li>
    <% end %>
  </ul>
<% else %>
  <h2>No listings</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pillow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, url: [current_user, listing]) do |form| %>
  <!--
  <-% if listing.errors.any? %>
    <div style="color: red;">
      <h2><-%= pluralize(listing.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <-% listing.errors.each do |error| %>
          <li><-%= error.full_message %></li>
        <-% end %>
      </ul>
    </div>
  <-% end %>
-->
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Update listing</h1>

<%= render "form", listing: @listing %>

app/views/listings/new.html.erb
<h1>Post a new listing!</h1>

<%= render "form", listing: @listing  %>

app/views/shared/_navbar.html.erb
<div class="nav">
  <div class="nav_logo">
    <%= link_to root_path do %>
      <%= image_tag "logotype.svg", class: 'nav_logo_image' %>
    <% end %>
  </div>
  <div class="nav_session_portal">
    <%= link_to "Welcome", welcome_path %>
    <% if current_user %>
      <span>Logged in as: <%= link_to current_user.email, user_path(current_user), id: 'user-profile' %></span>
      <%= link_to "Edit user profile", user_path(current_user) %>
      <%= button_to "Logout", :logout, method: :post, class: 'link' %>
    <% else %>
      <%= link_to "Sign in", :login %> /
      <%= link_to "Register", new_user_path %> 
    <% end %>
  </div>
</div>

<div class="flash_notices">
  <% if notice %><p id="notice"><%= flash[:notice] %></p><% end %>
  <% if alert %><p id="alert"><%= flash[:alert] %></p><% end %>
</div>

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<%= render "form" %>
<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to "#{user.email} page", user_path(user) %></li>
  <% end %>
</ul>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<span><%= @user.email %>'s page</span>
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

<hr>

<h2>User listings</h2>

<%= link_to "Post listing", new_user_listing_path(current_user) %>

<ul class="user_show_user_listings">
  <% @user.listings.each do |listing| %>
    <li>
      <%= listing.title %>
      <%= link_to "Edit listing", edit_user_listing_path(@user, listing) %>
      <%= button_to "Delete", user_listing_path(@user, listing), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p>If you see this your are logged in</p>

<p>Create a new listing!</p>

<%= link_to "New listing", new_user_listing_path(@user) %>